### ISSUE TITLE
Cahier des charges

### ISSUE THREAD

**Issue by ghost** [ProjetFilRougeCeppic2023/ProjetDocumentation#3]
Bonjour,  

pour pouvoir avoir accés facilement à votre cahier des charges et le modifier , 
ne pas mettre de fichier pdf ,
créer un fichier markdown avec le cahier des charges , 
nettement plus simple à faire et à modifier et au final à tracker car vous utilisez git.

**Comment by NoCared** [comment]
Bonjour,

Pas de problèmes, nous venons de le changer pour un markdown.
